apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buyerservice
  template:
    metadata:
      labels:
        app: buyerservice
    spec:
      containers:
        - name: buyerservice
          image: herbalmed/buyerservice:latest # replace with your Docker image name
          imagePullPolicy: Never
          ports:
            - containerPort: 8050 # replace with the port your app listens on

---
apiVersion: v1
kind: Service
metadata:
  name: buyerservice
spec:
  type: LoadBalancer
  ports:
    - port: 8050
      targetPort: 8050
      protocol: TCP
  selector:
    app: buyerservice
